import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import files from './asset-files.cjs';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const hash = createHash('sha1');
files.forEach(file => hash.update(fs.readFileSync(path.join(root, file))));
const version = hash.digest('hex').slice(0, 8);
const index = path.join(root, 'index.html');
fs.writeFileSync(index, fs.readFileSync(index, 'utf8').replace(/\?v=[0-9a-f]{8}/g, '?v=' + version));
console.log('Asset version: ' + version);
